# Generated by Django 4.2 on 2023-04-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamsapp', '0003_genre_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='genre',
            new_name='genres',
        ),
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(to='jamsapp.song'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('songs', models.ManyToManyField(to='jamsapp.song')),
            ],
        ),
    ]
