# Generated by Django 4.2 on 2023-04-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamsapp', '0006_alter_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='jamsapp.artist'),
        ),
    ]
